# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 
jobs:
  terraform:
    name: 'terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SECRET_ID: ${{ secrets.AZURE_SECRET_ID }}
      ARM_SECRET_VALUE: ${{ secrets.AZURE_SECRET_VALUE }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
      - uses: actions/checkout@v2

      - name: 'Terraform format'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './terraform'

      - name: 'terraform init'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './terraform'

      - name: 'terraform validate'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './terraform'

      - name: 'terraform plan'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './terraform'

      - name: 'terraform apply'
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@main
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'apply --auto-apply'
          tf_actions_working_dir: './terraform'


      